name: Desktop Critical Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - production

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted # tests run via Github self-hosted runner locally on laptop
    # runs-on: ubuntu-latest # tests run via Github.com cloud runner

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        # WebKit browser is intentionally excluded because it is not supported for MacOS 13
        run: npx playwright install chromium firefox --with-deps # install only chrome and firefox
        # run: npx playwright install --with-deps # installs all browsers

      - name: Decrypt Environment File
        env:
            ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
            ENV: ${{ inputs.environment }}
        run: |
            gpg --quiet --batch --yes --decrypt --passphrase="$ENV_PASSPHRASE" \
            --output .env.$ENV .env.$ENV.gpg
      
      - name: Run Desktop Critical Tests
        continue-on-error: true # subsequent steps run even when tests fail
        env:
          ENV: ${{ inputs.environment }}  
        run: |

          # get the filename (e.g., "desktop_tests.yml") from the full workflow reference path
          WORKFLOW_REF="${{ github.workflow_ref }}"
          WORKFLOW_FILE_PATH="${WORKFLOW_REF%@*}"       # Remove '@refs/heads/main'
          YML_FILENAME="${WORKFLOW_FILE_PATH##*/}"      # final value is only file name ex. "desktop_tests.yml"

          # get the test run's Playwright tags
          TEST_RUN_TAGS="(?=.*@platform-desktop)(?=.*@priority-critical)"

          # save to system variables that can be accessed later
          echo "TEST_RUN_TAGS=$TEST_RUN_TAGS" >> $GITHUB_ENV 
          echo "GITHUB_JOB_NAME=$YML_FILENAME" >> $GITHUB_ENV

          # launch test run
          npx playwright test --grep "$TEST_RUN_TAGS" --project="Github Chrome (Chromium)"

      - name: Verify Python & Pip Path
        run: |
          echo "=== Python Executable Path ==="
          which python3
          python3 --version

          echo "=== Pip Executable Path ==="
          which pip3 || which pip
          python3 -m pip --version

          echo "=== System PATH ==="
          echo $PATH    
      
      
      # - name: Save results to DB
      #   if: ${{ !cancelled() }}
      #   env:
      #     ENV: ${{ inputs.environment }}
      #     TEST_RUN_TAGS: ${{ env.TEST_RUN_TAGS }}
      #     GITHUB_JOB_NAME: ${{ env.GITHUB_JOB_NAME }}
      #   run: |
      #     python3 -m pip install psycopg2-binary python-dotenv
      #     python parse_and_save_playwright_results.py          

      - name: Upload Test Artifacts to GitHub Cloud
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts
          path: |
            playwright-report/
            results.json
          retention-days: 14
      