name: Desktop Critical Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - production

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted # tests run via Github self-hosted runner locally on laptop
    #runs-on: ubuntu-latest # tests run via Github.com cloud runner

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        # WebKit browser is intentionally excluded because it is not supported for MacOS 13
        run: npx playwright install chromium firefox --with-deps
        # run: npx playwright install --with-deps # installs all browsers

      - name: Decrypt Environment File
        env:
            ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
            ENV: ${{ inputs.environment }}
        run: |
            gpg --quiet --batch --yes --decrypt --passphrase="$ENV_PASSPHRASE" \
            --output .env.$ENV .env.$ENV.gpg
      
      - name: Run Desktop Critical Tests
        env:
          ENV: ${{ inputs.environment }}  
        #run: |

          # get the filename (e.g., "desktop_tests.yml") from the full workflow reference path
          # WORKFLOW_REF="${{ github.workflow_ref }}"
          # WORKFLOW_FILE_PATH="${WORKFLOW_REF%@*}"       # Remove '@refs/heads/main'
          # YML_FILENAME="${WORKFLOW_FILE_PATH##*/}"      # final value is only file name ex. "desktop_tests.yml"

          # get the test run's Playwright tags
          # TEST_RUN_TAGS="@platform-desktop.*@priority-critical|@priority-critical.*@platform-desktop"

          # save to system variables that can be accessed later
          # echo "TEST_RUN_TAGS=$TEST_RUN_TAGS" >> $GITHUB_ENV 
          # echo "GITHUB_JOB_NAME=$YML_FILENAME" >> $GITHUB_ENV

          # launch test run
          # npx playwright test --grep "$TEST_RUN_TAGS"
        run: npx playwright test --grep "@platform-desktop.*@priority-critical""

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30